# Generated by Django 6.0.3 on 2026-05-14 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('才藝', '才藝性社團'), ('體育', '體育性社團'), ('育樂', '育樂性社團'), ('學術類自然', '學術類自然社團'), ('學術類社會', '學術類社會社團')], default='才藝', max_length=10, verbose_name='社團屬性')),
                ('clubname', models.CharField(max_length=10, verbose_name='社團名稱')),
                ('leadername', models.CharField(max_length=5, verbose_name='社長名稱')),
                ('teachername', models.CharField(max_length=5, verbose_name='社師名稱')),
                ('memberaccount', models.CharField(default='40', max_length=3, verbose_name='社團名額')),
            ],
        ),
        migrations.CreateModel(
            name='Apply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant', models.CharField(max_length=5, verbose_name='申請者')),
                ('student_id', models.CharField(max_length=20, verbose_name='學號')),
                ('reason', models.TextField(blank=True, verbose_name='轉社原因')),
                ('status', models.IntegerField(choices=[(0, '待審核'), (1, '同意'), (2, '拒絕')], default=0, verbose_name='申請狀態')),
                ('targetclub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='em.club', verbose_name='想轉入的社團')),
            ],
        ),
    ]
