# Generated by Django 6.0.3 on 2026-05-14 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('em', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='memberaccount',
            field=models.CharField(default=40, max_length=3, verbose_name='社團名額'),
            preserve_default=False,
        ),
    ]
