# Generated by Django 6.0.3 on 2026-05-15 17:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('em', '0002_club_memberaccount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apply',
            name='reason',
        ),
        migrations.RemoveField(
            model_name='apply',
            name='targetclub',
        ),
        migrations.AddField(
            model_name='apply',
            name='from_club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='out_applies', to='em.club', verbose_name='原社團'),
        ),
        migrations.AddField(
            model_name='apply',
            name='in_reason',
            field=models.TextField(blank=True, null=True, verbose_name='轉入原因'),
        ),
        migrations.AddField(
            model_name='apply',
            name='out_reason',
            field=models.TextField(blank=True, null=True, verbose_name='轉出原因'),
        ),
        migrations.AddField(
            model_name='apply',
            name='target_club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='in_applies', to='em.club', verbose_name='想轉入的社團'),
        ),
        migrations.AlterField(
            model_name='apply',
            name='applicant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='申請者'),
        ),
        migrations.AlterField(
            model_name='apply',
            name='status',
            field=models.IntegerField(choices=[(0, '第一關：等待原社社長審核'), (1, '第一關失敗：原社社長拒絕'), (2, '第二關：等待原社社師審核'), (3, '第二關失敗：原社社師拒絕'), (4, '申請成功：允許轉出'), (5, '第三關：選取欲轉入社團並填寫資料'), (6, '第四關：等待新社社長審核'), (7, '第四關失敗：新社社長拒絕'), (8, '第五關：等待新社社師審核'), (9, '第五關失敗：新社社師拒絕'), (10, '第六關：等待組長審核'), (11, '第六關失敗：組長拒絕'), (12, '第六關成功：申請成功')], default=0, verbose_name='申請狀態'),
        ),
        migrations.AlterField(
            model_name='club',
            name='memberaccount',
            field=models.CharField(default='40', max_length=3, verbose_name='社團名額'),
        ),
    ]
