# Generated by Django 6.0.3 on 2026-05-21 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('em', '0003_remove_apply_reason_remove_apply_targetclub_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply',
            name='chief_approved',
            field=models.BooleanField(blank=True, null=True, verbose_name='原社社長審核'),
        ),
        migrations.AddField(
            model_name='apply',
            name='leader_approved',
            field=models.BooleanField(blank=True, null=True, verbose_name='訓育組長最終核定'),
        ),
        migrations.AddField(
            model_name='apply',
            name='new_chief_approved',
            field=models.BooleanField(blank=True, null=True, verbose_name='新社社長審核'),
        ),
        migrations.AddField(
            model_name='apply',
            name='new_teacher_approved',
            field=models.BooleanField(blank=True, null=True, verbose_name='新社老師審核'),
        ),
        migrations.AddField(
            model_name='apply',
            name='teacher_approved',
            field=models.BooleanField(blank=True, null=True, verbose_name='原社老師審核'),
        ),
    ]
