# Generated by Django 6.0.3 on 2026-05-22 02:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('em', '0004_apply_chief_approved_apply_leader_approved_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClubProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('社長', '社長'), ('老師', '老師'), ('組長', '組長')], max_length=10, verbose_name='職位/身分')),
                ('club', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='em.club', verbose_name='所屬社團')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='對應帳號(User)')),
            ],
            options={
                'verbose_name': '身分識別',
                'verbose_name_plural': 'Clubprofile',
            },
        ),
    ]
